import {
  Keyboard,
  Type,
  Languages,
  FileText,
  Zap,
  Sparkles,
  BookOpen,
  Heart,
  Music,
  Calendar,
  StickyNote,
} from "lucide-react";

export const baseApps = [
  {
    id: "LikDai",
    name: "LikDai",
    icon: Keyboard,
    gradient: "from-blue-500 to-purple-600",
    category: "language_tools",
    status: "available",
    badge: "popular",
  },
  {
    id: "FontConverter",
    name: "Font Converter",
    icon: Type,
    gradient: "from-emerald-500 to-teal-600",
    category: "converters",
    status: "available",
    badge: "new",
  },
  {
    id: "TaiLeConverter",
    name: "Tai Le Converter",
    icon: Languages,
    gradient: "from-orange-500 to-red-600",
    category: "converters",
    status: "available",
    badge: null,
  },
  {
    id: "ShanTranslit",
    name: "Shan Translit",
    icon: FileText,
    gradient: "from-pink-500 to-rose-600",
    category: "converters",
    status: "available",
    badge: null,
  },
  {
    id: "ShanSyllable",
    name: "Shan Syllable Work Break",
    icon: Zap,
    gradient: "from-indigo-500 to-blue-600",
    category: "converters",
    status: "available",
    badge: null,
  },
  {
    id: "TaiLeSyllable",
    name: "Tai Le Syllable Work Break",
    icon: Sparkles,
    gradient: "from-cyan-500 to-blue-600",
    category: "converters",
    status: "available",
    badge: null,
  },
  {
    id: "ShanWordSorting",
    name: "Shan Word Sorting",
    icon: BookOpen,
    gradient: "from-green-500 to-emerald-600",
    category: "utilities",
    status: "available",
    badge: null,
  },
  {
    id: "ShanProverbs",
    name: "Shan Proverbs",
    icon: Heart,
    gradient: "from-purple-500 to-pink-600",
    category: "cultural",
    status: "available",
    badge: "popular",
  },
  {
    id: "DokSu",
    name: "DokSu",
    icon: Music,
    gradient: "from-yellow-500 to-orange-600",
    category: "cultural",
    status: "available",
    badge: null,
  },
  {
    id: "PakPi",
    name: "PakPi",
    icon: Calendar,
    gradient: "from-red-500 to-pink-600",
    category: "cultural",
    status: "available",
    badge: null,
  },
  {
    id: "ShanNote",
    name: "Shan Note",
    icon: StickyNote,
    gradient: "from-teal-500 to-green-600",
    category: "utilities",
    status: "coming_soon",
    badge: "new",
  },
];
